[build]
  publish = "dist"
  command = "npm run build"

[functions]
  directory = "functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

# Enable function timeout for payment processing
[functions."initiate-payment"]
  timeout = 30

[functions."payment-status"]
  timeout = 30

[functions."payment-callback"]
  timeout = 30
