// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jodjakpgusmyimdzkawd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpvZGpha3BndXNteWltZHprYXdkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxODE5ODcsImV4cCI6MjA3Mzc1Nzk4N30.8AQ2WuqdRNLddTE3vILl1FNQQ5aGD-F9dcB67LaaaH0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});